# permissions for end users to view argocdmanageds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocdmanaged-viewer-role
rules:
- apiGroups:
  - pfe.opentlc.com
  resources:
  - argocdmanageds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pfe.opentlc.com
  resources:
  - argocdmanageds/status
  verbs:
  - get
