---
# tasks file for ArgoCDManaged
- name: Print message
  debug:
    msg: "Received request to add namespace {{ ansible_operator_meta.namespace  }} to ArgoCD namespace: {{ argocd_namespace }}"

- name: Update Namespace with argocd label
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ansible_operator_meta.namespace }}"
        labels:
          argocd.argoproj.io/managed-by: "{{ argocd_namespace }}"
